### ISSUE TITLE
Grafana カスタムダッシュボードのJSONをいい感じに管理したい

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/dreamkast-infra#1082]
なぜかJSON直書きしか頭になかった。これでよさそう。
```yaml
dashboards:
  default:
    custom-dashboard:
      # This is a path to a file inside the dashboards directory inside the chart directory
      file: dashboards/custom-dashboard.json
    local-dashboard:
      url: https://raw.githubusercontent.com/user/repository/master/dashboards/dashboard.json
```
https://github.com/grafana/helm-charts/tree/main/charts/grafana#import-dashboards

`inside the chart directory`はどこなのかよくわからない。`url`でやるつもり。
いずれにせよ、どこにJSONを置くかは決めないといけない。
