### ISSUE TITLE
Bump cert-manager from v1.5.3 to v1.6.1

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/dreamkast-infra#1198]
subtask of #1171

cert-manager 1.5は2021/12/7にEOLが予定されています。1ヶ月ありません。1.6に上げましょう。
https://cert-manager.io/docs/installation/supported-releases/

1.6でBreaking Changesがありますが、すでに`apiVersion: cert-manager.io/v1`を使用しているため影響はなさそうです。
> Breaking Changes (You MUST read this before you upgrade!)
Legacy cert-manager API versions are no-longer served
Following their deprecation in version 1.4, the cert-manager API versions v1alpha2, v1alpha3, and v1beta1 are no longer served.
> 
> This means if your deployment manifests contain any of these API versions, you will not be able to deploy them after upgrading. Our new cmctl utility or old kubectl cert-manager plugin can convert old manifests to v1 for you.

https://cert-manager.io/docs/release-notes/release-notes-1.6/

`targetRevision`の更新だけでよさそうです。
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/bce15b7c375062ca015558e82732e471569dc367/manifests/argocd-apps/dev/cert-manager.yaml#L17
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/bce15b7c375062ca015558e82732e471569dc367/manifests/argocd-apps/prd/cert-manager.yaml#L17

**Comment by jacopen** [comment]
やっちゃいましょうー。今なら割とこの辺自由に入れられます

**Comment by oke-py** [comment]
test.yaml
```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-dev-cloudnativedays-jp
spec:
  dnsNames:
  - 'test.dev.cloudnativedays.jp'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: test-dev-cloudnativedays-jp
```
```shell
kubectl apply -f test.yaml

# 90sぐらいでREADY: TRUEになった
kubectl get certificates test-dev-cloudnativedays-jp
NAME                          READY   SECRET                        AGE
test-dev-cloudnativedays-jp   True    test-dev-cloudnativedays-jp   97s

kubectl get secret test-dev-cloudnativedays-jp
NAME                          TYPE                DATA   AGE
test-dev-cloudnativedays-jp   kubernetes.io/tls   2      6m30s

kubectl get secret test-dev-cloudnativedays-jp -o jsonpath='{.data.tls\.crt}' | base64 -d | openssl x509 -text -noout -in -
Certificate:
    Data:
        ...
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = R3
        Validity
            Not Before: Dec 11 06:17:25 2021 GMT
            Not After : Mar 11 06:17:24 2022 GMT
        Subject: CN = test.dev.cloudnativedays.jp
        ...
```
