### ISSUE TITLE
緩やかにIRSAに移行したい

### ISSUE THREAD

**Issue by inductor** [cloudnativedaysjp/dreamkast-infra#1213]
## これはなに

現状、EKSのクラスター上で動くワークロードでAWSのIAMポリシーを必要とするものはInstance Roleを使って管理している
↓全部ではないがこんな具合

```yaml
  NodeInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - !FindInMap 
                  - ServicePrincipalPartitionMap
                  - !Ref 'AWS::Partition'
                  - EC2
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonEKS_CNI_Policy'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AWSElementalMediaLiveFullAccess'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonS3FullAccess'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonSESFullAccess'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonSQSFullAccess'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/CloudWatchAgentServerPolicy'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/CloudWatchSyntheticsReadOnlyAccess'
```

要件が増えるごとにどんどん肥大化しており、必要なIAM権限の整理が少しずつ大変になってきている。

そこで、[IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)に緩やかに移行していくことで、各ワークロードに必要なIAM権限をワークロードごとに分離するようにしたい

**Comment by inductor** [comment]
サンプルとして、Cluster Autoscaler及びAWS Load Balancer ControlelrをIRSAで動かす場合のやり方を記載しておく。

```sh
cat <<EOF > iam-ca.json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "autoscaling:DescribeAutoScalingGroups",
        "autoscaling:DescribeAutoScalingInstances",
        "autoscaling:DescribeLaunchConfigurations",
        "autoscaling:DescribeTags",
        "autoscaling:SetDesiredCapacity",
        "autoscaling:TerminateInstanceInAutoScalingGroup",
        "ec2:DescribeLaunchTemplateVersions"
      ],
      "Resource": ["*"]
    }
  ]
}
EOF

aws iam create-policy \
    --policy-name AWSClusterAutoscalerIAMPolicy \
    --policy-document file://iam-ca.json

CLUSTER_NAME=dreamkast
CLUSTER_REGION=ap-northeast-1
    
eksctl create iamserviceaccount \
--cluster=$CLUSTER_NAME \
--namespace=kube-system \
--name=cluster-autoscaler \
--attach-policy-arn=arn:aws:iam::`aws sts get-caller-identity | jq -r .Account`:policy/AWSClusterAutoscalerIAMPolicy \
--override-existing-serviceaccounts \
--region $CLUSTER_REGION \
--approve
helm repo add autoscaler https://kubernetes.github.io/autoscaler
helm repo update

helm upgrade --install cluster-autoscaler autoscaler/cluster-autoscaler  -n kube-system --set autoDiscovery.clusterName=$CLUSTER_NAME --set awsRegion=$CLUSTER_REGION --set rbac.serviceAccount.create=false --set rbac.serviceAccount.name=cluster-autoscaler
```

```sh
curl -o iam-policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.3.0/docs/install/iam_policy.json

aws iam create-policy \
    --policy-name AWSLoadBalancerControllerIAMPolicy \
    --policy-document file://iam-policy.json

CLUSTER_NAME=dreamkast
CLUSTER_REGION=ap-northeast-1

eksctl create iamserviceaccount \
--cluster=$CLUSTER_NAME \
--namespace=kube-system \
--name=aws-load-balancer-controller \
--attach-policy-arn=arn:aws:iam::`aws sts get-caller-identity | jq -r .Account`:policy/AWSLoadBalancerControllerIAMPolicy \
--override-existing-serviceaccounts \
--region $CLUSTER_REGION \
--approve


helm repo add eks https://aws.github.io/eks-charts
helm repo update

kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=$CLUSTER_NAME --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller
```

**Comment by oke-py** [comment]
失敗しても影響の小さそうなgrafanaから試してみようとしました。
以下のcfnスタックを作成しようとしたところロールバックされました。
> At least one of [Groups,Roles,Users] must be non-empty.

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Policy for grafana service account
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prd
    Description: dev or prd
Resources:
  Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "grafana-${Environment}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "cloudwatch:GetMetricData"
              - "cloudwatch:ListMetrics"
            Resource: '*'
```

IAMPolicyを先に作成しておき、eksctlでIAMRoleを作成しようと考えていたのですが。
こうですかね。

1. cfnでIAMPolicyとIAMRoleを作成する
2. `kubectl annotate`でServiceAccountに`eks.amazonaws.com/role-arn`を設定する
