### ISSUE TITLE
dev, prodでprometheus-operator, prometheus, node-exporterのバージョンを変えられるようにする

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/dreamkast-infra#1222]
devもprodもbaseを参照しているため、バージョン（に限りませんが）を更新しようとするとdevもprodもいっぺんに更新されてしまいます。
prometheusぐらいなら大丈夫だろうという気もしないではないですが、dev更新=>動作確認=>prod更新のステップを踏めるようにしておきたいです。

https://github.com/cloudnativedaysjp/dreamkast-infra/blob/4a233c06a156b0e815523b437511a884c1ca1423/manifests/infra/prometheus/overlays/development/kustomization.yaml#L1-L4
https://github.com/cloudnativedaysjp/dreamkast-infra/blob/4a233c06a156b0e815523b437511a884c1ca1423/manifests/infra/prometheus/overlays/production/kustomization.yaml#L1-L4

こんな感じでしょうか。overlaysを参照するものとbaseを参照するものの間に依存関係がある場合、どのように扱うといいのかkustomizeをよくわかっていません。
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
bases:
- ../../base
resources:
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/${ここを変える}/bundle.yaml
- ...
```
