### ISSUE TITLE
EBS CSI Driver導入検討

### ISSUE THREAD

**Issue by inductor** [cloudnativedaysjp/dreamkast-infra#1234]
現在、Dreamkast内でPVCを使うワークロードには以下のようなものがある

- Grafana
- Loki
- JaegerバックエンドのElasticsearch
- ReviewApps内部で使うMySQL

これらで内部的に使われるStorageClassは現状`gp2`が使われているが、これはCloud Provider AWSのin-tree実装である。

[CSI Driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver)を導入すると`gp3`がデフォルトに置き換わり、これはパフォーマンスコスト共に`gp2`よりも高い世代のブロックストレージである。

そこで、EBS CSI Driverの検証及び導入方法について検討したい。

**Comment by inductor** [comment]
https://github.com/aws/containers-roadmap/issues/1397#issuecomment-977610623

**Comment by inductor** [comment]
本番で見ると現状こんだけのpvcしかいないんで、現時点で問題になってないから雑に作り直してしまうというのも手ではある

```
kubectl get pvc -A
NAMESPACE    NAME                                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
monitoring   elasticsearch-master-elasticsearch-master-0   Bound    pvc-575328a9-7fa0-4ff1-b67f-29dde8f76a82   30Gi       RWO            gp2            3d3h
monitoring   elasticsearch-master-elasticsearch-master-1   Bound    pvc-da6cad43-51ad-4221-8109-7be122d99d9e   30Gi       RWO            gp2            3d3h
monitoring   elasticsearch-master-elasticsearch-master-2   Bound    pvc-a363c089-1cd2-4955-bc99-bbdcdd355d5e   30Gi       RWO            gp2            3d3h
monitoring   storage-grafana-0                             Bound    pvc-a58cc7ef-0bc4-45c9-8361-80b302206bf6   10Gi       RWO            gp2            24d
monitoring   storage-loki-0                                Bound    pvc-8af5da2e-552f-4782-b8e7-0c947feca913   10Gi       RWO            gp2            99d
```

**Comment by jacopen** [comment]
なるほど、やるならObservabilityチームが本格始動する前の今がベストタイミングかも

**Comment by inductor** [comment]
やるならこれでやれるかな
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp3
  encrypted: "true"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  fsType: ext4
  type: gp2
```
