### ISSUE TITLE
manifest以下の運用について課題感を共有する

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast-infra#751]

**Comment by ShotaKitazawa** [comment]
1, 2 について reviewapp-operator を作ればイケそうだとなってるのでプロトタイプ作ってレビュー可能な形まで進めようと思います

3 については、 dreamkast-infra からブランチを何個か切って実際に作ってみて、これもまたどれが一番分かりやすいかレビュー可能な形まで進めようと思います

**Comment by ShotaKitazawa** [comment]
reviewapp-operator を用いたリリースワークフローについての design doc を書きました。
後ほど然るべきところに転載します。

---

# Design of release workflow

## Background

以下のそれぞれの環境の提供を実現するリリースワークフローを作りたい。

- dev 環境: 開発対象のアプリケーション (以下 `app`) の動作確認用環境。 app を管理するリポジトリ (以下 `app リポジトリ`) の PR 1 つにつき 1 環境存在する
    - 以下、PR 作成に伴う dev 環境自動払い出しの仕組みを `reviewapp` という
- stg 環境: ステージング環境。app リポジトリの main ブランチの HEAD に紐付いて 1 環境のみ存在する
- prd 環境: プロダクション環境。app リポジトリの最近タグが打たれたコミットに紐づいて 1 環境のみ存在する

## Overview

- app リポジトリと別にマニフェストファイルを管理するリポジトリ (以下 `infra リポジトリ`) を用意し、各環境へのデプロイは全て Argo CD が infra リポジトリを参照し動作する
- dev 環境の実現のために [reviewapp-operator](https://github.com/cloudnativedaysjp/reviewapp-operator) を利用する
- stg, prd 環境の実現のために [Argo CD Image Updater](https://github.com/argoproj-labs/argocd-image-updater) を利用する

## Detailed design

各環境 (dev/stg/prd) それぞれにに対してアプリケーションがデプロイされるまでの流れを述べる。

### dev 環境へのデプロイ

dev 環境では [reviewapp-operator](https://github.com/cloudnativedaysjp/reviewapp-operator) により reviewapp が実現される。

reviewapp-operator は Argo CD と協調し以下のように動作する。

1. reviewapp-operator は app リポジトリの List PRs API を叩き、 reviewapp-operator の管理下にない PR を取得する。また、reviewapp-operator の管理下にある PR に対応するブランチの HEAD のコミットハッシュが更新されていた場合それを取得し手順2に進む
2. infra リポジトリ上の、 HEAD のコミットハッシュが更新された PR に紐づくマニフェストファイルを更新する
3. Argo CD はマニフェストの更新を検知し、クラスタにマニフェストを適用する
4. reviewapp-operator は Argo CD Application の更新を検知し、app リポジトリの特定の PR に対し更新された旨をコメントする

reviewapp-operator 自体についての詳細設計は以下を参照。

- https://miro.com/app/board/o9J_lwQb290=/ (Private Link)

### stg 環境へのデプロイ

stg 環境では [Argo CD Image Updater](https://github.com/argoproj-labs/argocd-image-updater) により新バージョンがデプロイされる。

Argo CD Image Updater は Argo CD の Application リソースに書かれた annotations からポーリング対象のコンテナレジストリを知り、対象のタグが更新されたときに infra リポジトリに対してイメージタグの更新用コミットを積むという動作をする。

以下に Argo CD の Application リソースに書く Argo CD Image Updater 用 annotations を例示する。
この例では「`docker.io/kanatakita/example01`, `docker.io/kanatakita/example02` レジストリにて `^main-.*$` にマッチするイメージタグが更新された場合、この Application が参照する infra リポジトリに書かれたイメージタグを更新する」という動作をする。

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >
      example01=docker.io/kanatakita/example01,
      example02=docker.io/kanatakita/example02
    argocd-image-updater.argoproj.io/example01.update-strategy: latest
    argocd-image-updater.argoproj.io/example01.allow-tags: regexp:^main-.*$
    argocd-image-updater.argoproj.io/example02.update-strategy: latest
    argocd-image-updater.argoproj.io/example02.allow-tags: regexp:^main-.*$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
```

Argo CD Image Updater を利用することで、 infra リポジトリ内の特定アプリケーション用マニフェストファイルに対しイメージタグの更新が走り、Argo CD がその更新を検知しマニフェストを適用することで新バージョンがデプロイされる。

### prd 環境へのデプロイ

prd 環境も stg 環境と同様の方法でデプロイされる。

## Alternatives considered

検討された代替案についてです。

### dreamkast-infra 上のマニフェストの image tag 更新

当リリースフローでは dreamkast-infra 上のマニフェストファイルに書かれたコンテナイメージのタグを更新することで、Argo CD がその更新を検知し Pod のロールアウトを実施することになる。
上述の通り、dev 環境では reviewapp-operator が、stg, prd 環境では argocd-image-updater がそれぞれ、マニフェストに書かれたコンテナイメージのタグ更新を行っている。

この方法の *Alternatives considered* として、「app リポジトリの更新トリガで動作する CI が infra リポジトリを更新しに行く」方法があるが、以下の欠点があるため不採用とした。

* App 開発者目線の欠点
    * アプリケーションリポジトリ内の CI 用設定ファイルに関して、そのアプリケーションのデプロイ先やデプロイ方法を理解して記述する必要がある
    * コンテナイメージをビルドするジョブに依存する形で各環境の infra リポジトリを更新する記述をしなければならず、その結果 CI で実施してる内容を読み解くコストが増える
* Infra 管理者目線の欠点
    * マニフェストファイルがどこから更新されるかをマニフェストファイルの配置先リポジトリのみを読むだけでは把握できない

### reviewapp の実現方法

reviewapp の実現方法の *Alternatives considered* として、「app リポジトリの更新トリガで動作する CI が infra リポジトリを更新しに行く」方法がある。
これは [dreamkast-infra 上のマニフェストの image tag 更新](#dreamkast-infra-上のマニフェストの-image-tag-更新) と同様の欠点がある他に、ジョブが他ジョブとの依存関係などの理由で失敗したときに infra リポジトリ等が意図しない状態になってしまうという問題もある。

具体例を挙げると、「PR を open した後すぐに close する」ことをしてしまった時、app リポジトリの CI で実現する方法だと「reviewapp 環境をクリーンアップするジョブが reviewapp 環境を構築するジョブよりも先に走ってしまい open な PR に紐付かない reviewapp 環境が残ってしまう」という問題がある。

対して、マニフェストファイルの設定内容に則して宣言的に動作する reviewapp-operator は上記を解決する代わりに、手続き的に動作するのに比べポーリング間隔のラグ分だけ reviewapp 用の環境が立ち上がるまでの時間が多くかかるという欠点がある。

これらの pros/cons を比較した結果、今回は宣言的に管理できる方を選択した。
